import { type WorkType } from 'shared/api/types/contracts';

export const workspaceCopy = {
    shiftFallback: 'Смена',
    loading: 'загрузка',
    mapHint: 'карта района · соберите план',
    emergency: 'Новая авария',
    emergencyPending: 'Пересчёт…',
    emergencyTitle: 'Новая авария в районе, план пересчитывается',
    emergencySubmit: 'Добавить аварию',
    slots: 'Расписание',
    panelAria: 'Список заявок',
    regionsLink: 'Районы',
    regionSwitchError: 'Не удалось переключить район',
    rebuildPlan: 'Пересобрать',
    rebuildPending: 'Считаем…',
    metricAssigned: 'в плане',
    metricUnassigned: 'без бригады',
    metricCompleted: 'готово',
    metricCrews: 'бригады',
    metricDistance: 'пробег',
    was: (value: string | number) => `было ${value}`,
    wasBaseline: (value: string | number) => `базовый ${value}`,
    wasPrevious: (value: string | number) => `до события ${value}`,
    buildGreeting: 'Подготовка смены',
    buildTitle: 'Распределите заявки',
    buildDescription:
        'Система подберёт бригады и построит маршруты. ' +
        'Проверьте заявки без бригады, затем контролируйте выполнение смены.',
    buildAction: 'Построить план',
    buildPending: 'Считаем маршруты…',
    ordersTab: 'Заявки',
    crewsTab: 'Маршруты',
    orderSearch: 'Тип, адрес или бригада',
    orderFilterAll: 'Все',
    orderFilterAssigned: 'Назначены',
    orderFilterOpen: 'Без бригады',
    orderFilterClosed: 'Закрыты',
    crewOnMap: (name: string) => `На карте · ${name}`,
    crewOnMapHint: 'Нажмите, чтобы вернуться ко всем заявкам',
    orderEmptyQuery: 'Ничего не нашлось',
    orderEmptyAssigned: 'Назначенных заявок нет',
    orderEmptyOpen: 'Все заявки распределены',
    orderEmptyClosed: 'Закрытых заявок нет',
    orderEmpty: 'Заявок нет',
    noSlot: 'без бригады',
    unassigned: 'не назначена',
    needsEnd:
        'Плановое время истекло. Подтвердите фактическое завершение, когда работа закончится.',
    alreadyOnSite: 'Уже на адресе',
    crewSearch: 'Найти бригаду',
    crewFilterAll: 'Все',
    crewFilterBusy: 'В плане',
    crewFilterFree: 'Без заданий',
    crewEmptyQuery: 'Никого не нашлось',
    crewEmpty: 'Бригад нет',
    crewUnavailable: 'недоступна',
    crewFree: 'нет заданий',
    crewEdit: 'Настроить',
    crewMakeUnavailable: 'Инженер недоступен',
    issuesTitle: 'Ошибки данных',
    changesTitle: 'Изменения',
    scheduleTitle: 'День бригад',
    scheduleHintAria: 'Как читать расписание',
    scheduleHintLegend: [
        { kind: 'work', label: 'работа' },
        { kind: 'travel', label: 'дорога' },
        { kind: 'idle', label: 'ожидание' },
    ] as const,
    scheduleHintKeys:
        '+ / − зум · 0 весь день · N к сейчас · ⌘ колесо вокруг курсора · пробел — рука',
    scheduleHintColors: [
        { tone: 'connection', label: 'подключение' },
        { tone: 'emergency', label: 'авария' },
        { tone: 'repair', label: 'ремонт' },
        { tone: 'additional', label: 'дозаказ' },
    ] as const,
    scheduleLive: 'На линии',
    scheduleTravel: 'дорога',
    scheduleOnLine: (count: number) => ` · ${count} на линии`,
    scheduleEmptyFilter: 'Нет бригад по этому фильтру',
    scheduleEmpty: 'После расчёта здесь появятся слоты каждой бригады',
} as const;

export const workTypeDotClass: Record<string, string> = {
    emergency: 'bg-destructive',
    connection: 'bg-primary',
    repair: 'bg-foreground',
    additional: 'bg-muted-foreground',
};

export const scheduleLayout = {
    pastPad: 72,
    visibleRows: 6,
    rowComfort: 40,
    rowDense: 32,
    hScroll: 14,
} as const;

export const crewPreviewNames = [
    'Соколов',
    'Мельникова',
    'Попов',
    'Иванов',
    'Кузнецов',
    'Смирнова',
    'Васильев',
    'Новикова',
    'Фёдоров',
    'Морозов',
    'Волкова',
    'Алексеев',
    'Лебедев',
    'Семёнова',
    'Егоров',
    'Павлов',
    'Козлова',
    'Степанов',
    'Николаев',
    'Орлова',
    'Андреев',
    'Макаров',
    'Никитина',
    'Захаров',
    'Зайцев',
    'Соловьёва',
    'Борисов',
    'Яковлев',
    'Григорьева',
    'Романов',
    'Воробьёв',
    'Сергеева',
    'Кузьмин',
    'Фролов',
    'Александрова',
    'Дмитриев',
    'Королёв',
    'Громова',
    'Белов',
    'Тарасов',
];

export const crewToneClass: Record<string, string> = {
    sokolov: 'bg-primary',
    melnikova: 'bg-foreground',
    popov: 'bg-muted-foreground',
};

export const workTypeBadge: Record<
    WorkType,
    'default' | 'secondary' | 'outline' | 'dark' | 'danger'
> = {
    emergency: 'danger',
    connection: 'default',
    repair: 'dark',
    additional: 'outline',
};
